<a href="https://colab.research.google.com/github/FidhaMariyam18/Pandas-Programming/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY-numerical python**

NumPy is a python library used for working with array.

import:import numpy as np

ndim used to check dimensions

array()is used to create array

In [ ]:
#Adding list
my_list1=[1,2,3]
my_list2=[4,5,6]
sum=print(my_list1+my_list2)

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np      #numpy make mathematical problems easier
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [ ]:
#one dimensional array
array1=np.array([7,8,9,4,6,8,1,2,3])
print(array1[2])   #indexing
print(array1[::2])   #slicing
print(array1.ndim)

9
[7 9 6 1 3]
1


In [ ]:
#two dimensional array
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.ndim)

2


In [ ]:
#three dimesional array
a1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a1.ndim)

3


In [ ]:
a2=np.array([[[1,2,3],
              [4,5,6]],

              [[7,8,9],
              [0,1,2]]])
print(a2[1,1,2])

2


In [ ]:
#converting 1D array to 2D array
arr1=np.array([1,2,3,4,5,6])
arr2=arr1.reshape(2,3)   #2:row 3:column
print(arr1)
print(arr2)
print(arr2.shape)   #used to check how many rows nd columns are available

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#zeros()
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
#ones()
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
#arange()
a=np.arange(1,11)   #ending number will not be printed
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#linspace()
a=np.linspace(0,20,4)  #randomly any 4 number within the range will be printed
print(a)

[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
#random()
a=np.random.rand(3)  #any 3 random number would be printed
print(a)

[0.89094303 0.30511553 0.60221527]


In [ ]:
import numpy as np
a=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(a[0,2,2])

9


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr1.reshape(2,2,3)
print(arr2)
print(arr2.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


**PANDAS-panel data system**


pandas is an open source python library

used for data cleaning,data analysis,data manipulation and data visualisation prepration

pandas works with Excel sheets or Tabular format data


**PANDAS DATA STRUCTURE** :-

they have mainly two type:

1.SERIES

2.DATA FRAMES

**IMPORT**:import pandas as pd

**SERIES** :it is a one dimensional labelled array

**DATA FRAMES**

In [ ]:
#SERIES

import pandas as pd
marks=pd.Series([1,2,3,4,5])
print(marks)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd
x=pd.Series([80,94,73,85],index=["maths","computer","physics","chemistry"])
print(x)

maths        80
computer     94
physics      73
chemistry    85
dtype: int64


In [ ]:
import pandas as pd
l=pd.Series(["BCA","BBA","BCOM"],index=["jack","john","joseph"])
print(l)
print(l["john"])

jack       BCA
john       BBA
joseph    BCOM
dtype: object
BBA


1.what is numpy and pandas?

numpy (numerical python) is a python library used for working with arrays.it make mathematical problems easier

pandas (panel data system) is an open source python library.it works with Excel sheets or Tabular format data


2.why do we use numpy and pandas?

numpy used for working with arrays perform  numerical operation

pandas used for data cleaning,data analysis,data manipulation and data visualisation prepration

3.what is series?

Series is a type of pandas data structure.it is a one dimensional labelled array

4.what is difference between list and numpy array?

list can store different data types.slower for numerical operations.support limited mathematical operation

numpy array can store elements in same data type.faster for numerical.support more mathematical operation

5.what is indexing and slicing?

indexing : accessing single element using position. syntax- variable_name[positon]

slicing : accessing muliple element from a sequence. syntax-variable_name[start:stop:step]

In [ ]:
#6.create a numpy array contain numbers from 1 to 20

x=np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#7.create a pandas series with doctors and department

import pandas as pd
l=pd.Series(["ORTHO","NEURO","ENT"],index=["jack","john","joseph"])
print(l)

jack      ORTHO
john      NEURO
joseph      ENT
dtype: object
